Feature branch
RaminMammadzada/EmbeddingImagesAndVideo pull request #7
Opened 2020-06-03 21:43 UTC by RaminMammadzada

The project is finished.

2020-06-04 03:08 UTC, tirthajyoti-ghosh commented
# Pull Request under review by Tirtha G. (TSE)

2020-06-04 05:05 UTC, tirthajyoti-ghosh commented
# Status: Changes required🚨
## Great job team! @RaminMammadzada and @Rocio01 

#### Kudos for the descriptive README 👏 and meaningful commit messages 🙌
However, your PR needs a little bit of work to do. Add a title to your PR with a short summary listing the work you have done on this project.

Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/. 

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

2020-06-05 06:23 UTC, peterrobert commented
### PULL REQUEST UNDER REVIEW BY PETER ROBERT

2020-06-05 07:03 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
Great work :clap: You have a descriptive readme file and you are using the proper git-flow guidelines :clap: 
However, there are a few issues that are preventing me from approving this project. Please work on the following changes.

- [ ] Your HTML code is not yet validated. Kindly validate it [here](https://validator.w3.org/#validate_by_input) and correct on all the errors
![validate](https://user-images.githubusercontent.com/32361963/83846292-0ba80780-a713-11ea-86b9-bb92bdc14032.png)

- [ ] Your CSS has some errors that need fixing. Kindly fix the errors. You can use [this site](https://jigsaw.w3.org/css-validator/) to validate your CSS.
![css](https://user-images.githubusercontent.com/32361963/83846495-59247480-a713-11ea-85d0-07b065546847.jpg)

Also fix the suggestions that I have made below.

Fix those errors and submit your project for another review.

You can also reach me via slack @peterrobert in case you need anything.

Happy coding:computer:

2020-06-05 07:03 UTC, peterrobert commented on index.html
> +    <!-- Main video and recommended videos sidebar sections -->
Remember semantic HTML. The main section of your code should be in the main tag.

2020-06-05 07:03 UTC, peterrobert commented on index.html
> +        <div class="Right">
You should add a title in this section to show that they are the coming up videos. Check the clone [here](https://www.youtube.com/watch?v=V74l_zS1x8E)

2020-06-05 07:03 UTC, peterrobert commented on index.html
> +                    <input type="text" name="text" class="search" placeholder="Search here!">
The search bar is well positioned :clap: But let's make it a bit long so that it looks like the [clone](https://www.youtube.com/watch?v=V74l_zS1x8E)

2020-06-05 08:49 UTC, RaminMammadzada commented
@peterrobert Thank you for deep review, I will correct them and submit it today again.

2020-06-06 00:51 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/RaminMammadzada/EmbeddingImagesAndVideo/feature-branch/index.html) shows good understanding and usage of Embedding Images and Videos. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @RaminMammadzada  & @Rocio01! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-17 08:36 UTC, merged